import type { BriefAnalysis } from "../engine/brief-analyzer";
import type { GeneratedCode } from "../engine/code-generator";
import type { DesignPlan } from "../engine/plan-generator";
import type { GeneratedProject, ProjectFile, ProjectFramework } from "./types";
import { validateGeneratedProject } from "./project-validator";

function slugify(value: string): string {
  const slug = value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 48);
  return slug || "verve-project";
}

function file(
  path: string,
  content: string,
  language: string,
  role: ProjectFile["role"] = "source"
): ProjectFile {
  return { path, content: content.trim() + "\n", language, role };
}

function projectReadme(
  name: string,
  framework: ProjectFramework,
  analysis: BriefAnalysis,
  plan: DesignPlan,
  scripts: Record<string, string>
): string {
  const isStaticHtml = framework === "html";
  const commands = isStaticHtml
    ? "- Open `index.html` directly in a browser.\n- Optional local server: `npx --yes serve .`"
    : Object.entries(scripts)
        .map(([key, command]) => `- \`npm run ${key}\` — \`${command}\``)
        .join("\n");
  const runCommand = isStaticHtml
    ? "# No install or build step is required.\n# Open index.html, or run:\nnpx --yes serve ."
    : "npm install\nnpm run dev";

  return `# ${name}

Generated by Verve Project Engine.

## Product brief

- Subject: ${analysis.subject}
- Audience: ${analysis.audience}
- Primary job: ${analysis.primaryJob}
- Tone: ${analysis.tone}
- Framework: ${framework}

## Design direction

${plan.layoutConcept}

Signature element: **${plan.signatureElement.name}** — ${plan.signatureElement.description}

## Run locally

\`\`\`bash
${runCommand}
\`\`\`

## Scripts

${commands || "No scripts are required."}

## Production contract

- Replace any placeholder content or assets with verified project material.
- Connect forms to a real endpoint before accepting submissions.
- Run the build and accessibility checks before deployment.
`;
}

function packageJson(
  name: string,
  scripts: Record<string, string>,
  dependencies: Record<string, string>,
  devDependencies: Record<string, string> = {}
): string {
  return JSON.stringify(
    { name, version: "1.0.0", private: true, scripts, dependencies, devDependencies },
    null,
    2
  );
}

function inferredDependencies(code: string): Record<string, string> {
  const dependencies: Record<string, string> = {};
  const imports = code.matchAll(/(?:from\s+|import\s*["'])([A-Za-z0-9@][A-Za-z0-9@/._-]*)["']/g);
  for (const match of imports) {
    const source = match[1];
    if (!source || source.startsWith(".") || source.startsWith("react") || source.startsWith("next")) continue;
    const packageName = source.startsWith("@") ? source.split("/").slice(0, 2).join("/") : source.split("/")[0];
    if (/^(?:@?[a-z0-9][a-z0-9._-]*)(?:\/[a-z0-9][a-z0-9._-]*)?$/i.test(packageName)) {
      dependencies[packageName] = "latest";
    }
  }
  return dependencies;
}

function readiness(warnings: string[]): GeneratedProject["readiness"] {
  return {
    status: warnings.length === 0 ? "ready" : "review-required",
    score: Math.max(0, 100 - warnings.length * 18),
  };
}

function finalizeProject(project: Omit<GeneratedProject, "validation"> | GeneratedProject): GeneratedProject {
  const { validation: _previousValidation, ...base } = project as GeneratedProject;
  void _previousValidation;
  const provisional = {
    ...base,
    validation: { status: "ready", score: 100, checks: [], failed: 0, warnings: 0 },
  } as GeneratedProject;
  const validation = validateGeneratedProject(provisional);
  const riskReadiness = readiness(provisional.warnings);
  const status = validation.status === "blocked"
    ? "blocked"
    : validation.status === "review-required" || riskReadiness.status === "review-required"
      ? "review-required"
      : "ready";
  return {
    ...provisional,
    validation,
    readiness: { status, score: Math.min(validation.score, riskReadiness.score) },
  };
}

function nextProject(
  name: string,
  generated: GeneratedCode,
  analysis: BriefAnalysis,
  plan: DesignPlan
): GeneratedProject {
  const dependencies = { next: "^16.3.1", react: "^19.2.4", "react-dom": "^19.2.4", ...inferredDependencies(generated.code) };
  const scripts = { dev: "next dev", build: "next build", start: "next start" };
  const files = [
    file("app/page.tsx", generated.code, "tsx"),
    file(
      "app/layout.tsx",
      `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: ${JSON.stringify(analysis.subject)},
  description: ${JSON.stringify(analysis.primaryJob)},
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}`,
      "tsx"
    ),
    file(
      "app/globals.css",
      `* { box-sizing: border-box; }
html { scroll-behavior: smooth; }
body { margin: 0; min-height: 100vh; }
button, input, textarea, select { font: inherit; }
img, svg { display: block; max-width: 100%; }
@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after { scroll-behavior: auto !important; animation-duration: 0.01ms !important; animation-iteration-count: 1 !important; transition-duration: 0.01ms !important; }
}`,
      "css"
    ),
    file("next.config.ts", `import type { NextConfig } from "next";\n\nconst nextConfig: NextConfig = {};\nexport default nextConfig;`, "typescript", "config"),
    file(
      "tsconfig.json",
      JSON.stringify({ compilerOptions: { target: "ES2017", lib: ["dom", "dom.iterable", "esnext"], allowJs: false, skipLibCheck: true, strict: true, noEmit: true, esModuleInterop: true, module: "esnext", moduleResolution: "bundler", resolveJsonModule: true, isolatedModules: true, jsx: "react-jsx", incremental: true, plugins: [{ name: "next" }], paths: { "@/*": ["./*"] } }, include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"], exclude: ["node_modules"] }, null, 2),
      "json",
      "config"
    ),
    file("next-env.d.ts", `/// <reference types="next" />\n/// <reference types="next/image-types/global" />`, "typescript", "config"),
    file("package.json", packageJson(name, scripts, dependencies, { "@types/node": "^20", "@types/react": "^19", "@types/react-dom": "^19", typescript: "^5" }), "json", "config"),
    file(".gitignore", "node_modules\n.next\nout\n.env*\n!.env.example", "text", "config"),
    file("README.md", projectReadme(name, "nextjs", analysis, plan, scripts), "markdown", "documentation"),
  ];

  const warnings = inspectProductionRisks(generated.code);
  return finalizeProject({ schemaVersion: 1, name, framework: "nextjs", entryFile: "app/page.tsx", files, dependencies, scripts, warnings, readiness: readiness(warnings) });
}

function reactProject(
  name: string,
  generated: GeneratedCode,
  analysis: BriefAnalysis,
  plan: DesignPlan
): GeneratedProject {
  const dependencies = { react: "^19.2.4", "react-dom": "^19.2.4", ...inferredDependencies(generated.code) };
  const scripts = { dev: "vite", build: "tsc -b && vite build", preview: "vite preview" };
  const files = [
    file("src/App.tsx", generated.code, "tsx"),
    file("src/main.tsx", `import { StrictMode } from "react";\nimport { createRoot } from "react-dom/client";\nimport App from "./App";\nimport "./index.css";\n\ncreateRoot(document.getElementById("root")!).render(<StrictMode><App /></StrictMode>);`, "tsx"),
    file("src/index.css", `* { box-sizing: border-box; }\nbody { margin: 0; min-width: 320px; min-height: 100vh; }\nbutton, input, textarea, select { font: inherit; }`, "css"),
    file("index.html", `<!doctype html>\n<html lang="en"><head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>${analysis.subject}</title></head><body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body></html>`, "html"),
    file("vite.config.ts", `import { defineConfig } from "vite";\nimport react from "@vitejs/plugin-react";\n\nexport default defineConfig({ plugins: [react()] });`, "typescript", "config"),
    file("tsconfig.json", JSON.stringify({ compilerOptions: { target: "ES2022", useDefineForClassFields: true, lib: ["ES2022", "DOM", "DOM.Iterable"], allowJs: false, skipLibCheck: true, esModuleInterop: true, allowSyntheticDefaultImports: true, strict: true, forceConsistentCasingInFileNames: true, module: "ESNext", moduleResolution: "Bundler", resolveJsonModule: true, isolatedModules: true, noEmit: true, jsx: "react-jsx" }, include: ["src"], references: [] }, null, 2), "json", "config"),
    file("package.json", packageJson(name, scripts, dependencies, { "@types/react": "^19", "@types/react-dom": "^19", "@vitejs/plugin-react": "latest", typescript: "^5", vite: "latest" }), "json", "config"),
    file(".gitignore", "node_modules\ndist\n.env*\n!.env.example", "text", "config"),
    file("README.md", projectReadme(name, "react", analysis, plan, scripts), "markdown", "documentation"),
  ];

  const warnings = inspectProductionRisks(generated.code);
  return finalizeProject({ schemaVersion: 1, name, framework: "react", entryFile: "src/App.tsx", files, dependencies, scripts, warnings, readiness: readiness(warnings) });
}

function htmlProject(
  name: string,
  generated: GeneratedCode,
  analysis: BriefAnalysis,
  plan: DesignPlan
): GeneratedProject {
  const scripts = {};
  const files = [
    file("index.html", generated.code, "html"),
    file("README.md", projectReadme(name, "html", analysis, plan, scripts), "markdown", "documentation"),
  ];
  const warnings = inspectProductionRisks(generated.code);
  return finalizeProject({ schemaVersion: 1, name, framework: "html", entryFile: "index.html", files, dependencies: {}, scripts, warnings, readiness: readiness(warnings) });
}

export function inspectProductionRisks(code: string): string[] {
  const warnings: string[] = [];
  if (/innerHTML|dangerouslySetInnerHTML/i.test(code)) warnings.push("Unsafe HTML injection API detected; verify every input source.");
  if (/<form\b/i.test(code) && !/action=|onSubmit=|addEventListener\(["']submit/i.test(code)) warnings.push("A form is present without a verifiable submission contract.");
  if (/alert\(["'][^"']*(success|sent|submitted)/i.test(code)) warnings.push("A success message may be simulated without a real backend.");
  if (/https?:\/\/(fonts\.googleapis|api\.fontshare|images\.unsplash)/i.test(code)) warnings.push("Runtime third-party asset dependency detected.");
  if (!/prefers-reduced-motion/i.test(code)) warnings.push("Reduced-motion handling was not detected in the generated entry file.");
  return warnings;
}

export function buildGeneratedProject(
  generated: GeneratedCode,
  analysis: BriefAnalysis,
  plan: DesignPlan,
  validationIssues: string[] = []
): GeneratedProject {
  const name = slugify(analysis.subject);
  const project = generated.framework === "html"
    ? htmlProject(name, generated, analysis, plan)
    : generated.framework === "react"
      ? reactProject(name, generated, analysis, plan)
      : nextProject(name, generated, analysis, plan);
  if (validationIssues.length > 0) {
    project.warnings.push(...validationIssues.map((issue) => `Validation: ${issue}`));
  }
  return finalizeProject(project);
}

export function buildRecoveryProject(
  brief: string,
  framework: ProjectFramework,
  failedStage: string
): GeneratedProject {
  const name = slugify(brief.slice(0, 48));
  const safeBrief = brief.replace(/[<>&]/g, (character) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;" })[character] ?? character);
  const html = `<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Verve recovery draft</title>
<style>:root{color-scheme:dark;font-family:Arial,sans-serif}body{margin:0;background:#0d0e10;color:#f4f0e8}.shell{min-height:100vh;display:grid;place-items:center;padding:clamp(24px,7vw,96px)}main{max-width:900px;border:1px solid #34363c;padding:clamp(28px,6vw,72px);background:#15171b}small{color:#ff6a3d;letter-spacing:.14em;text-transform:uppercase}h1{font-size:clamp(48px,10vw,112px);line-height:.9;margin:.5em 0}p{max-width:65ch;color:#b7bac1;line-height:1.7}</style></head>
<body><div class="shell"><main><small>Recovery draft · ${failedStage}</small><h1>Direction saved.<br>Generation can resume.</h1><p>${safeBrief}</p><p>Verve preserved this local fallback because the selected model stopped before delivering the complete project. Retry in Fast mode or choose another model for the production build.</p></main></div></body></html>`;
  const files = [file("index.html", html, "html"), file("README.md", `# Recovery draft\n\nThe provider stopped during **${failedStage}**. The original brief has been preserved in index.html.`, "markdown", "documentation")];
  const warnings = [`Provider stopped during ${failedStage}. This is a recovery preview, not the production project.`];
  return finalizeProject({ schemaVersion: 1, name: `${name}-${framework}-recovery`, framework: "html", entryFile: "index.html", files, dependencies: {}, scripts: {}, warnings, readiness: readiness(warnings) });
}
